default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
  # adapter: postgresql
  # database: railway
  # username: postgres
  # password: mbu3IykzbqifDnrHoFlV
  # host: containers-us-west-58.railway.app
  # port: 5617
  # pool: 5
